export const GET_ADVERT = "GET_ADVERT";
export const ADD_ADVERT = "ADD_ADVERT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS"; 